"""Metadata de los 20 reportes del Centro de Reportes (13 simples + 7 compuestos empaquetados / 4 analytics)."""
from __future__ import annotations

from typing import Any

REPORTS: dict[str, dict[str, Any]] = {
    "GM-S01": {
        "code": "GM-S01",
        "type": "simple",
        "title": "Cola de solicitudes de propiedad",
        "area": "Administración de Plataforma",
        "question": "¿Qué solicitudes de propiedad de juegos siguen sin decidir?",
        "description": "Listado de claims pendientes de revisión por administración.",
        "source": "fact_partner_games · submission_status",
        "columns": [
            {"key": "game_name", "label": "Juego", "align": "left"},
            {"key": "company_name", "label": "Estudio", "align": "left"},
            {"key": "contact_email", "label": "Correo", "align": "left"},
            {"key": "product_id", "label": "Product ID", "align": "left"},
            {"key": "submission_status", "label": "Estado", "align": "left"},
            {"key": "created_at_iso", "label": "Solicitado", "align": "right"},
        ],
        "filters": ["status"],
    },
    "GM-S02": {
        "code": "GM-S02",
        "type": "simple",
        "title": "Historial de liquidaciones",
        "area": "Administración de Plataforma",
        "question": "¿Qué pagos a estudios ya quedaron registrados?",
        "description": "Liquidaciones (payouts) pagadas a publishers, con método y referencia.",
        "source": "fact_partner_payouts",
        "columns": [
            {"key": "payout_id", "label": "Payout ID", "align": "left"},
            {"key": "partner_id", "label": "Partner ID", "align": "left"},
            {"key": "company_name", "label": "Estudio", "align": "left"},
            {"key": "amount", "label": "Monto (USD)", "align": "right"},
            {"key": "method", "label": "Método", "align": "left"},
            {"key": "status", "label": "Estado", "align": "left"},
            {"key": "reference", "label": "Referencia", "align": "left"},
            {"key": "paid_at_iso", "label": "Pagado", "align": "right"},
        ],
        "filters": [],
    },
    "GM-S03": {
        "code": "GM-S03",
        "type": "simple",
        "title": "Tickets de soporte abiertos",
        "area": "Atención al Cliente",
        "question": "¿Qué solicitudes de ayuda siguen abiertas?",
        "description": "Tickets con estado open/closed, ordenados por prioridad y fecha.",
        "source": "fact_support_tickets",
        "columns": [
            {"key": "ticket_id", "label": "Ticket", "align": "left"},
            {"key": "user_id", "label": "Usuario", "align": "left"},
            {"key": "subject", "label": "Asunto", "align": "left"},
            {"key": "priority", "label": "Prioridad", "align": "left"},
            {"key": "status", "label": "Estado", "align": "left"},
            {"key": "created_at_iso", "label": "Creado", "align": "right"},
        ],
        "filters": ["status"],
    },
    "GM-S04": {
        "code": "GM-S04",
        "type": "simple",
        "title": "Listado de empleados",
        "area": "Administración de Plataforma",
        "question": "¿Quiénes están registrados como personal de la empresa?",
        "description": "Empleados activos en emp_records (colección empleados).",
        "source": "emp_records · collection = empleados",
        "columns": [
            {"key": "nombre", "label": "Nombre", "align": "left"},
            {"key": "apellido", "label": "Apellido", "align": "left"},
            {"key": "cargo", "label": "Cargo", "align": "left"},
            {"key": "departamento", "label": "Departamento", "align": "left"},
            {"key": "email", "label": "Email", "align": "left"},
            {"key": "fecha_ingreso", "label": "Ingreso", "align": "right"},
            {"key": "salario", "label": "Salario", "align": "right"},
        ],
        "filters": [],
    },
    "GM-S05": {
        "code": "GM-S05",
        "type": "simple",
        "title": "Listado de contratos",
        "area": "Administración de Plataforma",
        "question": "¿Qué acuerdos comerciales existen y en qué estado están?",
        "description": "Contratos empresariales registrados en emp_records.",
        "source": "emp_records · collection = contratos",
        "columns": [
            {"key": "publicador", "label": "Publicador", "align": "left"},
            {"key": "tipo", "label": "Tipo", "align": "left"},
            {"key": "fecha_inicio", "label": "Inicio", "align": "left"},
            {"key": "fecha_fin", "label": "Fin", "align": "left"},
            {"key": "valor", "label": "Valor", "align": "right"},
            {"key": "estado", "label": "Estado", "align": "left"},
        ],
        "filters": [],
    },
    "GM-S06": {
        "code": "GM-S06",
        "type": "simple",
        "title": "Estado de trabajos ETL",
        "area": "Administración de Plataforma",
        "question": "¿Los trabajos de carga están idle, running, ok o en error?",
        "description": "Estado actual de cada job del servidor ETL.",
        "source": "etl_server · GET /etl/status",
        "columns": [
            {"key": "job", "label": "Trabajo", "align": "left"},
            {"key": "status", "label": "Estado", "align": "left"},
            {"key": "mensaje", "label": "Mensaje", "align": "left"},
        ],
        "filters": [],
    },
    "GM-S07": {
        "code": "GM-S07",
        "type": "simple",
        "title": "Campañas de marketing",
        "area": "Ventas y Marketing",
        "question": "¿Qué campañas existen y cuál es su estado?",
        "description": "Campañas promocionales registradas en emp_records.",
        "source": "emp_records · collection = campanas_marketing",
        "columns": [
            {"key": "nombre", "label": "Nombre", "align": "left"},
            {"key": "juego", "label": "Juego", "align": "left"},
            {"key": "presupuesto", "label": "Presupuesto", "align": "right"},
            {"key": "canal", "label": "Canal", "align": "left"},
            {"key": "estado", "label": "Estado", "align": "left"},
            {"key": "fecha_inicio", "label": "Inicio", "align": "left"},
            {"key": "fecha_fin", "label": "Fin", "align": "left"},
        ],
        "filters": [],
    },
    "GM-S08": {
        "code": "GM-S08",
        "type": "simple",
        "title": "Catálogo de distribución",
        "area": "Ventas y Marketing",
        "question": "¿Qué títulos están autorizados para comercializarse?",
        "description": "Catálogo comercial interno (distribución).",
        "source": "emp_records · collection = catalogo_distribucion",
        "columns": [
            {"key": "juego", "label": "Juego", "align": "left"},
            {"key": "plataforma", "label": "Plataforma", "align": "left"},
            {"key": "precio", "label": "Precio", "align": "right"},
            {"key": "region", "label": "Región", "align": "left"},
            {"key": "estado", "label": "Estado", "align": "left"},
        ],
        "filters": [],
    },
    "GM-S09": {
        "code": "GM-S09",
        "type": "simple",
        "title": "Ubicaciones destacadas activas",
        "area": "Ventas y Marketing",
        "question": "¿Qué juegos tienen promoción de visibilidad activa?",
        "description": "Placements featured pagados por estudios.",
        "source": "fact_featured_placements",
        "columns": [
            {"key": "game_name", "label": "Juego", "align": "left"},
            {"key": "partner_id", "label": "Partner", "align": "left"},
            {"key": "company_name", "label": "Estudio", "align": "left"},
            {"key": "status", "label": "Estado", "align": "left"},
            {"key": "amount_paid", "label": "Pagado (USD)", "align": "right"},
            {"key": "duration_days", "label": "Días", "align": "right"},
            {"key": "ends_at_iso", "label": "Termina", "align": "right"},
        ],
        "filters": [],
    },
    "GM-S10": {
        "code": "GM-S10",
        "type": "simple",
        "title": "Biblioteca / compras de jugadores",
        "area": "Comercio digital",
        "question": "¿Qué juegos compraron los usuarios?",
        "description": "Compras registradas (no eliminadas) en fact_purchases.",
        "source": "fact_purchases",
        "columns": [
            {"key": "user_id", "label": "Usuario", "align": "left"},
            {"key": "game_name", "label": "Juego", "align": "left"},
            {"key": "amount", "label": "Precio (USD)", "align": "right"},
            {"key": "refunded", "label": "Reembolsado", "align": "left"},
            {"key": "purchased_at_iso", "label": "Comprado", "align": "right"},
        ],
        "filters": [],
    },
    "GM-S11": {
        "code": "GM-S11",
        "type": "simple",
        "title": "Compras elegibles a reembolso",
        "area": "Comercio digital",
        "question": "¿Cuáles compras todavía pueden devolverse?",
        "description": "Compras dentro de 14 días y sin reembolso previo.",
        "source": "fact_purchases · ventana 14 días",
        "columns": [
            {"key": "user_id", "label": "Usuario", "align": "left"},
            {"key": "game_name", "label": "Juego", "align": "left"},
            {"key": "amount", "label": "Monto (USD)", "align": "right"},
            {"key": "purchased_at_iso", "label": "Comprado", "align": "right"},
            {"key": "days_left", "label": "Días restantes", "align": "right"},
        ],
        "filters": [],
    },
    "GM-S12": {
        "code": "GM-S12",
        "type": "simple",
        "title": "Juegos reclamados por estudio",
        "area": "Distribución B2B",
        "question": "¿Qué juegos ha solicitado administrar un estudio?",
        "description": "Claims de un partner (pending/approved/rejected).",
        "source": "fact_partner_games · partner_id",
        "columns": [
            {"key": "game_name", "label": "Juego", "align": "left"},
            {"key": "product_id", "label": "Product ID", "align": "left"},
            {"key": "submission_status", "label": "Estado", "align": "left"},
            {"key": "created_at_iso", "label": "Solicitado", "align": "right"},
        ],
        "filters": ["partner_id"],
    },
    "GM-S13": {
        "code": "GM-S13",
        "type": "simple",
        "title": "Liquidaciones recibidas por estudio",
        "area": "Distribución B2B",
        "question": "¿Qué payouts ya recibió un estudio?",
        "description": "Historial de liquidaciones filtrado por partner.",
        "source": "fact_partner_payouts · partner_id",
        "columns": [
            {"key": "payout_id", "label": "Payout ID", "align": "left"},
            {"key": "amount", "label": "Monto (USD)", "align": "right"},
            {"key": "method", "label": "Método", "align": "left"},
            {"key": "status", "label": "Estado", "align": "left"},
            {"key": "reference", "label": "Referencia", "align": "left"},
            {"key": "paid_at_iso", "label": "Pagado", "align": "right"},
        ],
        "filters": ["partner_id"],
    },
    "GM-C01": {
        "code": "GM-C01",
        "type": "compound",
        "title": "Resumen económico de plataforma",
        "area": "Administración de Plataforma",
        "question": "¿Cuánto GMV, comisión y adeudo a publishers acumula GameMetrics?",
        "description": "Indicadores agregados de GMV, ingresos de plataforma y saldo adeudado.",
        "source": "fact_partner_ledger (agregación OLAP)",
        "columns": [
            {"key": "metric", "label": "Indicador", "align": "left"},
            {"key": "value", "label": "Valor", "align": "right"},
            {"key": "unit", "label": "Unidad", "align": "left"},
        ],
        "filters": [],
    },
    "GM-C02": {
        "code": "GM-C02",
        "type": "compound",
        "title": "Ganancias por estudio",
        "area": "Distribución B2B",
        "question": "¿Cuánto ha ganado un estudio (bruto, fee, neto y saldo disponible)?",
        "description": "Resumen de earnings de un publisher con desglose por juego.",
        "source": "fact_partner_ledger · fact_partner_payouts",
        "columns": [
            {"key": "game_name", "label": "Juego", "align": "left"},
            {"key": "units_sold", "label": "Unidades", "align": "right"},
            {"key": "gross_revenue", "label": "Bruto (USD)", "align": "right"},
            {"key": "platform_fee", "label": "Comisión (USD)", "align": "right"},
            {"key": "publisher_net", "label": "Neto (USD)", "align": "right"},
        ],
        "filters": ["partner_id"],
    },
    "GM-C03": {
        "code": "GM-C03",
        "type": "compound",
        "title": "Desempeño comercial por estudio",
        "area": "Ventas y Marketing",
        "question": "¿Qué estudios venden más y cuáles concentran más reembolsos?",
        "description": "Rollup por partner: unidades, bruto, comisión, neto y reembolsos.",
        "source": "fact_partner_accounts + fact_partner_ledger",
        "columns": [
            {"key": "company_name", "label": "Estudio", "align": "left"},
            {"key": "games_count", "label": "Juegos", "align": "right"},
            {"key": "units_sold", "label": "Unidades", "align": "right"},
            {"key": "gross_revenue", "label": "Bruto (USD)", "align": "right"},
            {"key": "platform_fee", "label": "Comisión (USD)", "align": "right"},
            {"key": "publisher_net", "label": "Neto (USD)", "align": "right"},
            {"key": "refund_count", "label": "Reembolsos", "align": "right"},
            {"key": "status", "label": "Estado", "align": "left"},
        ],
        "filters": [],
    },
    "GM-C04": {
        "code": "GM-C04",
        "type": "compound",
        "title": "Volumen de catálogo por semana",
        "area": "Analytics BI",
        "question": "¿Cuántos videojuegos hay en la semana seleccionada?",
        "description": "Conteo total de fact_videogames filtrado por semana ETL.",
        "source": "fact_videogames · COUNT por semana",
        "columns": [
            {"key": "semana", "label": "Semana", "align": "right"},
            {"key": "total_juegos", "label": "Total juegos", "align": "right"},
        ],
        "filters": ["week"],
    },
    "GM-C05": {
        "code": "GM-C05",
        "type": "compound",
        "title": "Juegos por género (semana)",
        "area": "Analytics BI",
        "question": "¿Cómo se distribuye el catálogo por género en la semana?",
        "description": "Agregación de géneros del catálogo analítico.",
        "source": "fact_videogames · GROUP BY genres",
        "columns": [
            {"key": "genre", "label": "Género", "align": "left"},
            {"key": "game_count", "label": "Juegos", "align": "right"},
        ],
        "filters": ["week"],
    },
    "GM-C06": {
        "code": "GM-C06",
        "type": "compound",
        "title": "Juegos por plataforma (semana)",
        "area": "Analytics BI",
        "question": "¿Cómo se distribuye el catálogo por plataforma en la semana?",
        "description": "Agregación de plataformas del catálogo analítico.",
        "source": "fact_videogames · GROUP BY platforms",
        "columns": [
            {"key": "platform", "label": "Plataforma", "align": "left"},
            {"key": "game_count", "label": "Juegos", "align": "right"},
        ],
        "filters": ["week"],
    },
    "GM-C07": {
        "code": "GM-C07",
        "type": "compound",
        "title": "Top 10 juegos por calificación",
        "area": "Analytics BI",
        "question": "¿Cuáles son los 10 títulos mejor valorados de la semana?",
        "description": "Ranking por rating en fact_videogames.",
        "source": "fact_videogames · ORDER BY rating DESC LIMIT 10",
        "columns": [
            {"key": "rank", "label": "#", "align": "right"},
            {"key": "name", "label": "Juego", "align": "left"},
            {"key": "rating", "label": "Rating", "align": "right"},
            {"key": "metacritic", "label": "Metacritic", "align": "right"},
            {"key": "genres", "label": "Géneros", "align": "left"},
        ],
        "filters": ["week"],
    },
}


def list_catalog() -> list[dict[str, Any]]:
    order = [
        "GM-S01", "GM-S02", "GM-S03", "GM-S04", "GM-S05", "GM-S06", "GM-S07",
        "GM-S08", "GM-S09", "GM-S10", "GM-S11", "GM-S12", "GM-S13",
        "GM-C01", "GM-C02", "GM-C03", "GM-C04", "GM-C05", "GM-C06", "GM-C07",
    ]
    return [REPORTS[c] for c in order]


def get_meta(code: str) -> dict[str, Any] | None:
    return REPORTS.get((code or "").upper())
